# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installed package list
      run: apt list --installed
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    # Chromium is already installed!
    - name: Install software
      run: sudo apt install -y chromium-browser
    - name: Install all necessary packages
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests beautifulsoup4 pandas webdriver-manager selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        export PYTHONPATH=src
        pytest




